### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by daxpedda**
It's unfortunate that we can't check code behind nightly guards without having to switch to nightly Clippy.

### CODE REVIEW

**Comment by ModProg** [comment]
looks like CI is still failing?

**Comment by daxpedda** [comment]
Yes, found a bug in the CI configuration ...

**Comment by daxpedda** [comment]
Man, still ... I have no clue whats going on with the CI here.

**Comment by daxpedda** [comment]
Yeah, it's correct now ... I really dislike YAML.

**Review by ModProg — APPROVED** [review]

**Pull request merged**
