### PR TITLE
Make `discriminant` function `const`

### PR DESCRIPTION
**Pull request by daxpedda**
Split off from #81.

### CODE REVIEW

**Review by ModProg — APPROVED** [review]
This would only leave the `as` code

**Comment by ModProg** [comment]
```rs
fn main() {
    dbg!(hello());
}

const fn hello() -> u8 {
    200_u8.pow(2)
}
```

runs in release without issues.

While 
```rs
const fn hello() -> u8 {
    const A: u8 = 200_u8.pow(2);
    A
}
```

fails to compile

**Comment by ModProg** [comment]
So while this definitly doesn't hurt, as the function can be const, it doesn't improve the issue at all.

**Comment by daxpedda** [comment]
Oh yeah, it doesn't actually fix our problem, I just added it help the compiler :sweat_smile:.

**Pull request merged**
